version: 0.2

env:
  variables:
    FRONTEND_DIR: "AWS_CICD_PIPELINE/frontend"
    LAMBDA_DIR: "AWS_CICD_PIPELINE/lambda"
    CFN_DIR: "AWS_CICD_PIPELINE/cloudformation"

phases: 
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing NPM dependencies..."
    build:
      commands:
        - echo "Building lambda project..."
        - cd lambda
        - zip -r ../LambdaFunction.zip .
        - cd ..
    post_build:
      commands:
        - echo "Uploading to S3..."
artifacts:
  files:
    - LambdaFunction.zip
    - AWS_CICD_PIPELINE/cloudformation/**