AWSTemplateFormatVersion: '2010-09-09'
Description: Creating EC2 instance with Lambda and Role Stack

Parameters:
  InstanceType:
    Type: String 
    Default: t3.micro
    Description: EC2 instance type

Resources:
  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./roles.yml

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMRolesStack
    Properties:
      TemplateURL: ./lambda.yml

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0861f4e788f5069dd
      KeyName: key-0c48f47c612d61bee
      SecurityGroups:
        - !Ref CiCdPipelineSG
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "Welcome to the Static Frontend on EC2!" > /var/www/html/index.html

  CiCdPipelineSG: 
    Type: AWS::EC2::SecurityGroup 
    Properties: 
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          